export const Blanco = {
    // Estos colores se usan en TODO el proyecto cambiar SOLO cuando sea necesario
    Tipo: 'image/png',
    Data: 'iVBORw0KGgoAAAANSUhEUgAAANUAAACpCAYAAAC8oHg5AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAHuSURBVHhe7dMxAQAgDMCwgX/PwIGEnslTBV3nGSCzf4GIqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpipoKYqSBmKoiZCmKmgpipIGYqiJkKYqaCmKkgZiqImQpSMxcoPgVO2geECAAAAABJRU5ErkJggg==',
  }

 




